### ISSUE TITLE
100,000 /sec is... a lot -> ES tweaks?

### ISSUE THREAD

**Issue by mrdavidlaing** [sacheendra/es_benchmark#1]
Great article! - http://news.appbase.io/scaling-elasticsearch-writes/ - Thanks.

Raised some interesting internal discussion following our performance testing work - http://www.logsearch.io/blog/2015/05/performance-testing-elasticsearch.html - which only achieved order of magnitude slower indexing rates:

> 100,000 /sec is... a lot. However, they're not indexing log messages in these tests. They're only using a corpus of about 24 words which will end up being indexed and a single field. Makes for _extremely_ simple indexing whereas a typical log message has several dozen index references to append per message. It's still much more indexing than I would have thought - I suspect they're using some other tweaks which they don't mention in the article.

Do you have some additional ES tweaks you can share?

**Comment by siddharthlatest** [comment]
Thanks for the comment! Since indexing is a CPU intensive operation, we found that the performance is heavily dependent on the number of nodes, and in fact we observed a linear correlation till 25 nodes (we hit our AWS provision limits to test on more, but I suspect this correlation holds on even beyond). How many nodes did your ES cluster run on?

I see that your best trial setup was using the C4.2xlarge nodes (4884 messages / seconds), which is the same as we ran on. We don't have any extra tweaks except like you say, we are indexing on something simpler than logs. Document size plays a role in the indexing throughput, so a more raw measure like merge rate might be a better comparison figure. At our peak with 24 nodes, we see ~ 130 MB/s indexing rate.

**Comment by mrdavidlaing** [comment]
@siddharthlatest - thanks for the feedback.

What kind/size of disks did you provision?  Did you use POIPs?

**Comment by siddharthlatest** [comment]
We use 200 GB standard SSDs with the baseline IOPS of 600/3000 (3 per GiB).

**Comment by mrdavidlaing** [comment]
@siddharthlatest - Thanks - that is pretty much what we are using.  The trick of provisioning nice big SSDs to get good baseline IOPS is a good one :)
